### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by alissn** [laravel-modules-com/docs#7]
There are some design issues observed in the Laravel Module documentation:

- When scrolling down, the top left corner remains empty.
- Inability to scroll to the end of the menu list, resulting in the latest item not being shown.

![image](https://github.com/laravel-modules-com/docs/assets/26966142/68123b46-854e-43b0-8e17-eb54fd80e4fd)

**Comment by dcblogdev** [comment]
thanks, sorted it.
